program: src/train.py
method: bayes
metric:
  goal: maximize
  name: best_avg_reward
parameters:
  learning_rate:
    distribution: log_uniform
    min: -11.5 # math.log(1e-5)
    max: -6.9 # math.log(1e-3)
  gamma:
    values:
      distribution: log_uniform
      min: -0.1 # math.log(0.9)
      max: -0.001 # math.log(0.999)
